export const GET_SCHEDULE_SETTINGS_REQUEST = 'GET_SCHEDULE_SETTINGS_REQUEST'
export const GET_SCHEDULE_SETTINGS_FAILURE = 'GET_SCHEDULE_SETTINGS_FAILURE'
export const GET_SCHEDULE_SETTINGS_SUCCESS = 'GET_SCHEDULE_SETTINGS_SUCCESS'
export const SET_SCHEDULE_SETTINGS = 'SET_SCHEDULE_SETTINGS'